### ISSUE TITLE
Move reports selection tab to menubar-sebmenu

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#23]
1) At the moment, the menu item for 'View Reports' takes us to a page where we can select different reports - this page is not needed, the different reports can be different sub-menu items e.g. 'Sector report'. 'Location Report' etc

2) At the moment, when you click on a report, there is also a tab for 'reports panel' this is not needed as all the reports can now be accessed via the top manu

**Comment by raashidahmad** [comment]
Fixed. On the reports page, i see the tab, will remove the tab in the next deployment.

**Comment by matmaxgeds** [comment]
Just leaving this open until it is fixed in a deployment

**Comment by raashidahmad** [comment]
Fixed

**Comment by matmaxgeds** [comment]
Strange - I still see it
![screenshot from 2019-02-23 23-29-03](https://user-images.githubusercontent.com/432153/53292442-e1069980-37c2-11e9-8cd8-9fa4a2b13065.png)

**Comment by raashidahmad** [comment]
I did not see on the current deployment. If you find it through any specific steps. Please guide me about those steps.
