### ISSUE TITLE
Hide the registration link, contact buttons etc for the Reports launch

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#418]
@raashidahmad - so that we can launch the reports side only, then we need to hide a few things:

1. Registration button
2. Contact buttons
3. Suggest a change buttons
4. Any other ones you can think of?

We should combine this with moving our testing server to a new one i.e. #401

**Comment by raashidahmad** [comment]
Done, probably i will revert it in the next deployment as the launch plan has been changed.

**Comment by matmaxgeds** [comment]
I am still seeing 'suggest a change' on the project profiles? Also we want users to be able to make reports from the 2019 data from now until we launch, so the change will need reverting, but only on the second (testing) server, not the one that is currently hosting aims.mop.gov.so

**Comment by raashidahmad** [comment]
@matmaxgeds I am little confused about this, Pau said, we are not doing any launch this year, but as you said, this means we are doing this launch on some date? Is this correct? So that i can implement this ticket then.

**Comment by matmaxgeds** [comment]
@raashidahmad lets discuss on the call in an hour

**Comment by raashidahmad** [comment]
@matmaxgeds Okay thanks

**Comment by matmaxgeds** [comment]
@raashidahmad confirming that we will need this to launch as 'reports only' version in December, that should prove to people that we are progressing and buy us the last bit of time we need for finishing the data entry to launch early next year.

**Comment by raashidahmad** [comment]
Updated.
