### ISSUE TITLE
FY names and management pages

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#458]
- [ ] We no longer need a management page for "Financial Years" as they are not user editable
- [ ] At the moment, there is a FY 1918/19.....this is 100 years ago, and should only be shown in the list for reports, if there is a project with disbursements in the year (which there should not be!)
- [ ] Please rename the management page "Financial Year Settings" to "Financial Years" now that this name is available again

**Comment by raashidahmad** [comment]
1. Done
2. This is fixed
3. Matt, These two pages are doing two different things:
      (a) Financial year settings sets the starting month and day of the financial year
      (b) Financial years, then adjust start day actually creates the financial year for the current financial  year

**Comment by matmaxgeds** [comment]
I am afraid:

1. I still don't understand why we need both as surely when the user sets the FY start date, and clicks save, then the FYs needed are generated.

2. ....what happens if you set different dates for
a) http://aims.mop.gov.so/financial-year-settings
b) http://aims.mop.gov.so/financial-years

**Comment by raashidahmad** [comment]
Okay let me try to explain:

1. Financial year settings means that you are telling the system that Your financial year starts from 1st of the April or 1st of July any date. These settings will be used to allot financial year to the project when it is created.
2. The second option is when user tries to manually create the financial year, for example, FY 2020. This is just a UI facility to create the current financial year, if it is not created yet. Do you think it is not required?

**Comment by matmaxgeds** [comment]
Thanks @raashidahmad that is helpful.

The only user input we want, is for them to set the start date (day/month) of the FY. The system should do the rest i.e. generating a table of FYs (do not need to be visible in the management UI), and working out which FY a project/disbursement is in.

Does that make sense?

**Comment by raashidahmad** [comment]
@matmaxgeds Yes got it now, will remove the one which is not required. Thanks

**Comment by raashidahmad** [comment]
Updated.
